# Generated by Django 6.1.1 on 2026-10-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='City Dental Hospital', max_length=200)),
                ('tagline', models.CharField(default='Your Smile, Our Priority', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('about', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('patients_count', models.PositiveIntegerField(default=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/')),
            ],
        ),
    ]
