# Generated by Django 6.1.1 on 2026-10-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=300)),
                ('specialization', models.CharField(blank=True, max_length=300)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
